# Generated by Django 4.1 on 2022-09-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecapstoneapi', '0002_remove_feedback_slot_user_delete_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('action_pic', models.ImageField(null=True, upload_to='assets')),
            ],
        ),
    ]
